name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Step for building the application
    - name: Build
      run: npm build # Replace with your project's build command

    - name: Code linting with Pylint
      run: |
        pip install pylint
        pylint *.py

    - name: Unit testing with pytest
      run: |
        pip install pytest
        pytest

    - name: Static Application Security Testing with CodeQL
      uses: github/codeql-action/analyze@v1

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/my-cloud-project/my-app:latest .
        echo ${{ secrets.GCR_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/my-cloud-project/my-app:latest

    - name: Scan the Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'gcr.io/your-project/your-app:latest'
        format: 'table'
        exit-code: '1'

    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment.yaml
    
