name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Code linting with Pylint
      run: |
        pip install pylint
        pylint src/*.py

    - name: Unit testing with pytest
      run: |
        pip install pytest
        pytest

    - name: Static Application Security Testing with CodeQL
      uses: github/codeql-action/analyze@v1

    - name: Build Docker Image
      run: docker build -t gcr.io/luminous-bazaar-401220/flask-app:latest .

    - name: Push Docker Image to Google Artifact Registry
      env:
        GCR_JSON_KEY: ${{ secrets.GCR_KEY }}
      run: |
        echo "$GCR_JSON_KEY" | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/luminous-bazaar-401220/flask-app:latest


    - name: Scan the Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'gcr.io/luminous-bazaar-401220/flask-app:latest'
        format: 'table'
        exit-code: '1'

    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment.yaml
    
